### ISSUE TITLE
CanvasContext can't draw (colored) rectangles

### ISSUE THREAD

**Issue by sschmidTU** [0xfe/vexflow#638] opened 2018-08-02 14:30 UTC
SVGContext does this fine, but canvascontext.clearRect() only draws transparent rectangles, and rect() does nothing.
You can see for yourself in this [fiddle demo](https://jsfiddle.net/sschmidTU/jvw0ecxz/).
(or see [this screenshot](https://user-images.githubusercontent.com/33069673/43590362-1c111972-9671-11e8-837a-07e99c14fdb7.png))

I looked at the code and tried hard to fix it, but no cigar. I tried to set the backgroundFillColor in CanvasContext in multiple ways.

I also don't fully understand the way the context object is handled in canvascontext. In the constructor it saves a context object as a new property under a new name, and then uses it for all draw calls. Does it use the functions in SVGContext? Or RaphaelContext? It's a lot of duplicate code as well.

What i want to use this for is drawing a rectangle as background for the Canvas image, which by default is transparent. Using Canvas, you can right-click on the image and save it, but you'll get a transparent background instead of white, so you need more image editing. It's not as convenient to save an SVG as image, unfortunately.

If we can fix this, i'll add visual regression tests for colored backgrounds.

**Comment by 0xfe** [comment] 2018-08-02 22:34
Thanks for reporting. I was able to replicate the SVG behaviour in your jsfiddle with the following code:

```javascript
var contextCanvas = rendererCanvas.getContext();
contextCanvas.setFillStyle("blue");
contextCanvas.fillRect(0,0,500,200);
contextCanvas.setFillStyle("black");

... rest of your code ...
```

So it looks like the API methods need to be rationalized.

**Comment by sschmidTU** [comment] 2018-08-02 23:17
@0xfe that's already helpful, i'll use that for now, thanks!

**Comment by gristow** [comment] 2018-08-03 02:26
By the way @sschmidTU, here's a quick method I use to grab a png from `SVGContext`:

``` javascript
  downloadPNG(fileName) {
    const s = new window.XMLSerializer();
    s.serializeToString(this.svgContext.svg);

    const data = this.exportSVG();
    const canvas = document.createElement('canvas');
    // because I need higher resolution...
    canvas.style.width = `${this.width * 5}px`;
    canvas.style.height = `${this.height * 5}px`;
    canvas.width = this.width * 5;
    canvas.height = this.height * 5;
    const ctx = canvas.getContext('2d');
    const DOMURL = window.URL || window.webkitURL || window;

    const img = new window.Image();
    const svgBlob = new window.Blob([data], { type: 'image/svg+xml;charset=utf-8' });
    const url = DOMURL.createObjectURL(svgBlob);

    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      DOMURL.revokeObjectURL(url);

      const imgURI = canvas
        .toDataURL('image/png')
        .replace('image/png', 'image/octet-stream');

      const evt = new window.MouseEvent('click', {
        view: window,
        bubbles: false,
        cancelable: true
      });

      const a = document.createElement('a');
      a.setAttribute('download', `${ (fileName || 'utheory-sandbox') }.png`);
      a.setAttribute('href', imgURI);
      a.setAttribute('target', '_blank');

      a.dispatchEvent(evt);
    };

    img.src = url;
  }
```

**Comment by rvilarl** [comment] 2021-07-16 05:10
@0xfe @sschmidTU can this one be closed or is there anything to do?

**Comment by sschmidTU** [comment] 2021-07-16 22:11
Well, the problem isn't solved as far as i know, CanvasContext can't do what it should be able to do (and what SVGContext can).

**Comment by ronyeh** [comment] 2021-09-30 22:55
I worked on this code recently while cleaning up APIs for my PR: https://github.com/ronyeh/vexflow/blob/setFont/src/canvascontext.ts

@sschmidTU What do you want clearRect() and rect() to do?

As far as I can tell, `clearRect()` is doing the correct thing on CanvasContext.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearRect

It draws a transparent black rectangle (which is like "cutting a rectangular hole" through the canvas). This exposed anything on the webpage that was underneath the canvas.

If you need to fill a rectangle, `fillRect()` is the method you want.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillRect

`rect()` doesn't actually draw anything immediately:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/rect

> Like other methods that modify the current path, this method does not directly render anything.  To draw the rectangle onto a canvas, you can use the fill() or stroke() methods.

CanvasContext pretty much works as intended, because we pass method calls on to its internal CanvasRenderingContext2D.

It's SVGContext that is doing the "wrong thing". We try to make SVGContext as similar to CanvasRenderingContext2D as possible, but sometimes it is impossible (or very very difficult).

For example, `clearRect()` would require us to modify existing paths on the SVG object, so that we can effectively "cut the hole" into all shapes that the clearRect() intersects with. As a workaround, we just draw a filled white box to pretend that we cut that hole.

@sschmidTU I would suggest we close this issue, as fillRect() and .fillStyle are the correct way to draw a filled-in rectangle.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle#changing_the_fill_color_of_a_shape

If there's a related bug that needs to be addressed, we can open a new bug and reference this one in the discussion. That'll help bump up important issues to the top, since I assume bugs from 2018 (or earlier) will not be addressed anytime soon. ;-)

**Comment by ronyeh** [comment] 2021-09-30 23:10
I think the main issue is that we tried to make SVGContext have the same API as CanvasContext, but then we supercharged SVGContext's methods to do more than expected. :-)

From your jsfiddle up top:
```
var contextSVG = rendererSVG.getContext();
contextSVG.setBackgroundFillStyle("blue");
contextSVG.clearRect(0,0,500,200);           // draws transparent rectangle
contextSVG.rect(0,0,500,200, {fill:"blue"});  // does the same thing

``` 

Here, SVGContext is doing the "wrong thing" in that it is not following the CanvasRenderingContext2D spec.

@0xfe I would suggest that we have SVGContext follow the CanvasRenderingContext2D spec as closely as possible, to avoid confusion.

If we want supercharged methods (for example: fill a rect immediately with a style attributes object), we should name the method differently so it's clear that it's a convenience method that we built in.

For example, SVGContext's `rect()` currently accepts 5 params. [Canvas's only accepts 4](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/rect).

If we want to keep the 5 param version for SVGContext, we should rename it to:
```
fillRectWithStyle(x: number, y: number, width: number, height: number, style?: Attributes):
```

That way, we can also add this method to CanvasContext, for feature parity.

**Comment by sschmidTU** [comment] 2021-10-01 00:35
Yes, i wanted what SVGContext (erroneously) did with `clearRect()`, which was (clearing and) filling a rect with the background color.
You're right, `fillRect()` with `fillStyle` set is the correct way, so this can be closed.
I was just confused because SVGContext did what i wanted and CanvasContext behaved differently.

(one of my goals was to draw a white background at the start, which makes the image copied from the browser have an actual white background instead of transparent:)
![image](https://user-images.githubusercontent.com/33069673/135548324-e5617e5a-bc90-45de-a189-eaca6f5e9c01.png)
![image](https://user-images.githubusercontent.com/33069673/135548344-92f923e0-fd52-46ea-a5ae-68b2196ecfbd.png)

**Comment by ronyeh** [comment] 2021-10-01 00:56
So I think SVGContext is "buggy". We should work to make SVGContext identical (as much as possible) to CanvasContext. Then we can add extra convenience methods as desired.

**Comment by ronyeh** [comment] 2021-10-01 02:39
Your example is very useful, and is great feedback. I've noticed too, with our visual regression tests, that all the PNGs have transparent background. 

It makes sense that a developer would want a solid background color. This would be useful (someday) if we want to support dark mode websites (e.g., if for some reason the developer wants notes to be light gray and the score background to be black or dark gray).

If we don't already have an easy way to fill the score background (that works on both CanvasContext and SVGContext), then we should definitely make this happen!

**Comment by sschmidTU** [comment] 2021-10-01 15:16
> If we don't already have an easy way to fill the score background (that works on both CanvasContext and SVGContext), then we should definitely make this happen!

In my example, this seems to work to get a white background instead of transparent (as 0xfe commented):
```js
contextCanvas.setFillStyle("white");
contextCanvas.fillRect(0,0,500,200);
```

**Comment by ronyeh** [comment] 2021-11-14 17:37
OK, I'm going to close this as "solved" by the two lines of code Simon / Mohit provided.

**Closed by ronyeh** 2021-11-14 17:37 UTC
Labels: 4.0
