### ISSUE TITLE
Stick upwards

### ISSUE THREAD

**Issue by peterkroon** [0xfe/vexflow#299] opened 2015-08-22 14:43 UTC
How do I force the stick of the note upwards?
Is this possible?

**Comment by 0xfe** [comment] 2015-10-08 13:11
If you mean the stem, there is a `setStemDirection` function that you can call on a note.

(Closing this, since it's not a bug -- best place to ask questions is on the VexFlow google group.)

**Closed by 0xfe** 2015-10-08 13:11 UTC
