### ISSUE TITLE
x2 notehead is not standard 

### ISSUE THREAD

**Issue by ghost** [0xfe/vexflow#589] opened 2017-11-06 15:28 UTC
The x2 notehead, used in percussions for the ride cymbal and the Charleston is not standard. This should simply be a cross, like the x3 glyph but without the circle around.

Also, the stem is not properly set, it should start at the top right arm of the cross, currently it just goes too low.

**Comment by gristow** [comment] 2017-11-06 15:48
Could you provide images or a jsfiddle to better explain this issue?

**Comment by Prim3val** [comment] 2017-11-06 17:14
Please find on the left, a note rendered with Vexflow (notice that the stem is too long), and on the right, a standard charlestone-type note head.

![hh](https://user-images.githubusercontent.com/33401500/32454044-4e4f8a76-c31e-11e7-9734-49cef2bc2b40.png)

**Comment by PieterHartzer** [comment] 2018-08-22 11:50
I created a duplicate ([#640](https://github.com/0xfe/vexflow/issues/640)) of this issue and fixed it.  It's currently in a PR ([#641](https://github.com/0xfe/vexflow/pull/641)) and this ticket can be closed as a duplicate.  I would close mine but it's linked to the work and PR.  This is my mistake seeing as I created the ticket and fixed it without searching existing tickets.  Apologies.

**Comment by PieterHartzer** [comment] 2018-08-22 13:10
Duplicate of #640

**Comment by gregemerson** [comment] 2019-04-10 23:13
This seems to be fixed. 

In working with x2 notes, I found that a duration with an 'r' has no effect, i.e. the rest is ignored. There may be a problem caused by the overriden use of StaveNote.noteType. It is being used for 'r' and 'x2'. I am happy to look at the code but I'm sure there is someone here more fimiliar with the code and can find the necessary fix far faster than I can.

**Comment by PieterHartzer** [comment] 2019-04-18 14:32
@gregemerson How did you get on with this? I haven't got time to have a look at this yet (moving home).

**Closed** 2020-04-05 22:50 UTC
