### ISSUE TITLE
Using ES6 code will not allow using vexflow in some modern browsers (as of yet)

### ISSUE THREAD

**Issue by Huji** [0xfe/vexflow#440] opened 2016-08-28 22:53 UTC
In several places, ES6 syntax has been introduced for `const` declaration, but not every browser supports it yet. It appears Firefox won't support it until [version 51](https://bugzilla.mozilla.org/show_bug.cgi?id=1263355).

I think this issue should be left open, and a new release should not be created, until all major browsers support declarations like `for (const a in b)`. Until then, releases should be based on revisions prior to the implementation of ES6-style code.

**Comment by Silverwolf90** [comment] 2016-08-29 09:52
VexFlow is transpiled to ES5 using Babel. This allows us to write the source in ES6 while supporting ES5 compliant browsers. If you need to support IE <=10 then there is an unsupported legacy build available in `/releases`.

**Comment by Huji** [comment] 2016-08-29 16:18
No, IE <= 10 is not my concern. I am talking about Firefox 48 (latest release) which still doesn't support `for (const a in b)` syntax.

**Comment by aaronmars** [comment] 2016-08-29 16:49
Perhaps this is just a bug? I'd think `(let a in b)` would be appropriate here.  According to MDN, `for ... in` is supported in Firefox: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

**Comment by Huji** [comment] 2016-08-29 16:58
Yes, `for .. in` is support in firefox, what is not supported is for **const** a in b

**Comment by 0xfe** [comment] 2016-08-29 17:14
But shouldn't Babel transpile this down to what any (reasonable) modern browser will support?

**Comment by aaronmars** [comment] 2016-08-29 17:23
All I'm saying is that `const` makes no sense here since the variable being declared is, by definition, mutable. Maybe I'm missing something here, but I guess I'd just like to see if the same error pops up if `let` is used instead.

**Comment by Huji** [comment] 2016-08-29 17:26
I agree with that. I think the use of `const` here is uncalled for.

**Comment by 0xfe** [comment] 2016-08-29 17:30
Oh, right `const` doesn't make sense here, and our `eslint` rules won't let that code through anyway. @Huji Do you know where this is coming from? I did a quick search in `src/` and didn't see that pattern anywhere.

**Comment by Huji** [comment] 2016-08-29 18:05
@0xfe I just marked all those places where a `const` was inside a for loop. In all those cases use of `const` is uncalled for, since the object is mutable by definition.

**Comment by Huji** [comment] 2016-08-29 18:07
Here is another issue that also has to do with ES6:

At the very end of `src/vex.js` there is a line which reads:

```
export { Vex };
```

That throws an error message in Firefox:

```
SyntaxError: export declarations may only appear at top level of a module
```

This time, it is not just Firefox's limited ES6 support. The ES6, by definition, doesn't allow `export` anywhere except for at the top of the document. [See why](http://stackoverflow.com/questions/34203325/why-must-export-import-declarations-be-on-top-level-in-es2015)

I don't know how to fix this one though.

**Comment by 0xfe** [comment] 2016-08-29 20:06
Thinking about this more, they seem to be reasonable uses of `const`. Since `const` is lexically scoped, code like below suggests that the `const` variable is never reassigned in the block.

```javascript
for (const key of ['stave', 'renderer', 'font']) {
  Object.assign(this.options[key], options[key]);
}
```

This is equivalent to:

```javascript
const keys = ['stave', 'renderer', 'font'];
let i = 0;
do {
  const key = keys[i];
  Object.assign(this.options[key], options[key]);
  i += 1;
} (while i < keys.length);
```

I'm really surprised that Firefox doesn't like this because SlimerJS, which is based on Firefox, and used for the visual regression tests, has no problem with it.

**Comment by 0xfe** [comment] 2016-08-29 20:10
Okay, just downloaded Firefox (48.0.2) and ran the VexFlow tests, and everything worked fine. Not sure what's up with your environment @Huji. :-)

<img width="1253" alt="screen shot 2016-08-29 at 4 08 59 pm" src="https://cloud.githubusercontent.com/assets/241299/18065720/26e0fdec-6e03-11e6-98d9-aae2cbdfe88a.png">

**Comment by Huji** [comment] 2016-08-30 02:02
Um, okay I will test that too. But did you check the error log in the console?

**Comment by Silverwolf90** [comment] 2016-08-30 18:32
Since every test is wrapped in a try-catch (unless you check the `No try-catch` checkbox`) any errors thrown would be come up as a failing test.

**Comment by Silverwolf90** [comment] 2016-08-30 18:34
And just to confirm, @0xfe is absolutely right: `const` in a `for...of` is perfectly valid because the variable is initialized each iteration.

**Comment by Huji** [comment] 2016-08-30 18:41
I repeated it in Firefox 47.0.1 on Windows, and still get the error below when I open `src/transform.html`

![capture](https://cloud.githubusercontent.com/assets/84526/18102207/c3d9ea3e-6ebf-11e6-8373-bf9b0790a637.PNG)

**Comment by 0xfe** [comment] 2016-08-30 18:45
`transform.html` isn't using the compiled code. Please open `tests/flow.html`.

**Comment by Silverwolf90** [comment] 2016-08-30 18:48
Ah! Yes! 

I guess this means transform is broken -- it should probably be importing `/build/vexflow-debug.js` since no browsers support ES modules yet.

**Comment by 0xfe** [comment] 2016-08-30 21:40
I fixed `transform.html` in `master`, so it should be good.

I'm closing this issue until there's clearer evidence that there's actually a problem for the end user.

**Closed by 0xfe** 2016-08-30 21:40 UTC
