### ISSUE TITLE
JoinVoices / Formatter not aligning voices correctly on 3.0.9

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#839] opened 2021-02-19 22:05 UTC
Using native code in 1.2.93 I get a correct alignment between the voices
![image](https://user-images.githubusercontent.com/22865285/108566192-49cb7280-7306-11eb-9e71-f51d2cbd4eb6.png)

However in 3.0.9 I get it worng
![image](https://user-images.githubusercontent.com/22865285/108566304-7c756b00-7306-11eb-86cd-400c0ad53cdf.png)

The code is available in https://jsfiddle.net/zg95n0du/

**Comment by 0xfe** [comment] 2021-02-20 13:52
Looks like there's two different issues here: 1) `preCalculateMinWidth` bug which was fixed in a recent PR, and 2) some rests are not getting accounted for cross voice.

**Comment by rvilarl** [comment] 2021-02-20 17:35
I just built 1a6275c7b8e87 and I get, I believe, the same result

![image](https://user-images.githubusercontent.com/22865285/108603742-01fe2700-73aa-11eb-9d98-81ada348705e.png)

**Comment by 0xfe** [comment] 2021-02-22 12:10
Thanks, this is a super weird bug -- it seems like if I replace those 16th rests with 16th notes, the same problem exists. Will try to figure it out.

**Comment by AaronDavidNewman** [comment] 2021-02-24 03:01
I've been digging into the formatting code a little.  I think I see what is going on, but I can't do much more than restate the problem.  The problem seems to be that the duration ratios are not normalized across voices.

The function the formatter uses to get the ratio of available space based on its duration (softmax) is normalized by dividing by the sum of the softmaxes.  In this case, this sum in the bottom voice is much larger than that of the top.  And the un-normalized ratio of the first 8th in the bottom voice is larger than the 16th in the top, but not twice as large.  As a result, the computed ratios are almost the same and the ideal distance from the previous note ends up being the same.  And since distance is measured from the first note, they are aligned even though they shouldn't be.

This is weird in that it seems to have only to the specific combinations of durations in this example.  Even if you beam all the notes and add the missing dots to the 8th notes, the basic problem won't go away.  I don't think anything is missing or being miscounted.  And I don't think increasing the softmax parameter will help because the ratios end up the same.

I see there is some logic about multiple passes that is maybe supposed to kick in, but I am a long way from understanding all that.

**Comment by 0xfe** [comment] 2021-02-24 12:36
> The problem seems to be that the duration ratios are not normalized across voices.

Thanks for digging in. And good job on trying to understand the formatter -- I'd love for more people to understand that part, it helps me by providing a second pair of eyes, and reduces my debugging load :-)

That said... I thought I was explicitly normalizing across voices -- the softmax scaling uses all the ticks across all the voices in the denominator (`maxTicks`). Maybe `maxTicks` is incorrect?

> This is weird in that it seems to have only to the specific combinations of durations in this example. 

Any way to narrow this down to something more reproducable? E.g., if you swap the 8th and the 16th notes, does it still happen? Or if you replace and 8th with two 16th notes in a voice?

**Comment by rvilarl** [comment] 2021-02-24 20:45
These are simpler examples getting the same effect. Perhaps it helps in the debugging
![image](https://user-images.githubusercontent.com/22865285/109062661-7efe0900-76e8-11eb-9a37-d32e8b32c485.png)

https://jsfiddle.net/7xs1q9v3/

And avoiding the usage of dot.
![image](https://user-images.githubusercontent.com/22865285/109063067-00ee3200-76e9-11eb-8607-714f896b4751.png)

https://jsfiddle.net/7xs1q9v3/1/

**Comment by rvilarl** [comment] 2021-02-24 21:02
> Any way to narrow this down to something more reproducable? E.g., if you swap the 8th and the 16th notes, does it still happen? Or if you replace and 8th with two 16th notes in a voice?

Now with the simpler example, swaping notes, also wrong
![image](https://user-images.githubusercontent.com/22865285/109064256-773f6400-76ea-11eb-8e0e-5c841216227b.png)

https://jsfiddle.net/7xs1q9v3/2/

replacing the first 8th with two 16th, the result seems to be correct
![image](https://user-images.githubusercontent.com/22865285/109065483-f1241d00-76eb-11eb-9afb-4eff904a2c28.png)

https://jsfiddle.net/7xs1q9v3/3/

**Comment by AaronDavidNewman** [comment] 2021-02-24 21:53
>> Any way to narrow this down to something more reproducable?

My observation: when the first notes are 8th 16th in voice A and 16th 8th in voice B, and there are more notes in voice A.  If you reduce the number of notes in voice A, the formatting improves.  

>>  I thought I was explicitly normalizing across voices -

@0xfe by this I meant that the softmax factors are the same, but the expTicksUsed in each voice is different, and hence the ratio a note with a given duration will take up is different.  The maxTicks seem to be correct in both voices, as do the tick maps.

**Comment by AaronDavidNewman** [comment] 2021-02-24 21:57
To illustrate the point above.  Changing the 16th of voice B improves the formatting in voice A, seemingly:

![image](https://user-images.githubusercontent.com/5438280/109070860-a937d280-76b8-11eb-9377-9911dc2f7513.png)

![image](https://user-images.githubusercontent.com/5438280/109070940-c2408380-76b8-11eb-97d6-eaf2ddb1c1b2.png)

**Comment by rvilarl** [comment] 2021-02-25 18:17
I have test checking out previous versions of formatter.js using commit 1a6275c as basis for the rest of the sources.

It seems that the bug was introduced in commit c524472 "Improved cross-stave formatting"

The previous commit fdbf9c6 of formatter.js works correctly

**Comment by AaronDavidNewman** [comment] 2021-02-25 18:36
Great detective work.  I remember this was submitted to fix a couple of issues I opened about x-stave formatting:

https://github.com/0xfe/vexflow/issues/778
https://github.com/0xfe/vexflow/issues/779

  In fact if you run the current tests against the old formatter, you'll see what I mean.  It seems this fix broke some other cases where the staves are justified, but the notes don't line up very well.

**Comment by mscuthbert** [comment] 2021-02-25 19:23
There are a number of places where `.addTickable()` is still being called without a voiceIndex.  Maybe the function signature for `addTickable` should add a default index value of zero.  so `addTickable(tickable, voiceIndex=0)`?

**Comment by AaronDavidNewman** [comment] 2021-02-26 06:17
@mscuthbert are you referring to the calls to formatter.joinVoices having different results depending on whether you join multiple voices at once vs. each one separately?

I have a question about the formatter, the function `preFormat.shiftToIdealDistances:`

``` javascript
errorPx = (ideal.fromTickable.getX() + ideal.expectedDistance) - (x + spaceAccum);
```

Shouldn't that include the `fromTickable.width`?  In the 2/4 test case from @rvilarl , the first notes have width of 23px, and the `expectedDistance` to the next ticks are 9 and 18 respetively.  But the `fromTickable.getX()` of the first note is always 0.  So the starting distances are computed as 23, but actually they are close to 0.  If I add the width to this statement, the formatting is correct, proportionally, but the notes spill over the measure.

**Comment by rvilarl** [comment] 2021-02-26 22:01
> I have tested checking out previous versions of formatter.js using commit [1a6275c](https://github.com/0xfe/vexflow/commit/1a6275c7b8e8759bd0623c6dee0779a4ce7c84e7) as basis for the rest of the sources.
> 
> It seems that the bug was introduced in commit [c524472](https://github.com/0xfe/vexflow/commit/c5244724133848d9743dccb6cd327aab427d0a55) "Improved cross-stave formatting"
> 
> The previous commit [fdbf9c6](https://github.com/0xfe/vexflow/commit/fdbf9c65ff951e434b2855fa533d25e88872f239) of formatter.js works correctly

Looking further in the changes between these two commits I have seen that reverting the following area seems to resolve the problem, but notes also go over the measure indicating that preCalculateMinTotalWidth is not returning a value aligned with the change

![image](https://user-images.githubusercontent.com/22865285/109359426-c1108180-7885-11eb-97c0-63789de4bb35.png)

**Comment by AaronDavidNewman** [comment] 2021-02-27 00:15
I don't think it's that easy.  The old code just blindly adds the expected distance until it runs out of room.    But the expected distance isn't known when calculating the min width.  So there won't be any way to predict how much room the music will need, and also we want to condense the music when we can.  Reverting this section _does_ fix the justification of all these cases, though, at the expense of proportionality and each measure being way too long.

With the new code, what happens is some notes are too wide for the expected distance of the next note.  At the beginning of the measure this causes the notes to stay in their original X rather than being shifted to the right.  At the end of the measure, it causes the music to get bunched up and collide.   So all we need to do is 1) recognize when that happens, and 2) fix it somehow :)

**Comment by rvilarl** [comment] 2021-02-27 20:11
I am far from understanding how it works but I hope this helps identifying the bug.
Using commit 1a6275c.

I have seen that the function _**calculateIdealDistances**_ is the one calculating and returning
_**expectedDistance**_ and _**maxNegativeShiftPx**_ which decide how the compressed render will look like.

with no change I get:
![image](https://user-images.githubusercontent.com/22865285/109398019-69801d80-793a-11eb-9fad-45b316e5be66.png)

executing _**maxNegativeShiftPx = maxNegativeShiftPx / 3;**_ before returning the values I get:
![image](https://user-images.githubusercontent.com/22865285/109398079-b237d680-793a-11eb-9e5b-cd2cf320ba1f.png)

executing _**maxNegativeShiftPx = maxNegativeShiftPx / 3; expectedDistance = expectedDistance / 1.5;**_ before returning the values I get:
![image](https://user-images.githubusercontent.com/22865285/109398119-f3c88180-793a-11eb-8d89-01839cb9cfc1.png)

I believe that the problem might be related to the fact that the calculation of _**maxNegativeShiftPx**_ in _**calculateIdealDistances**_ considers the notes of a single voice. In the example: 
for _**tick 1024**_ the two first notes of the upper stave are considered and the intermediate values of _**insideLeftEdge, insideRightEdge**_ are _**25.868**_ and _**23.868**_  resulting in _**maxNegativeShiftPx**_ with value _**2**_
for _**tick 2048**_ the two first notes of the lower stave are considered and the intermediate values of _**insideLeftEdge, insideRightEdge**_ are _**39.802**_ and _**23.868**_ resulting in _**maxNegativeShiftPx**_ with value _**13.934**_

Using the calculated values _**2**_ and _**13.934**_ leave the second notes of each stave perfectly aligned.
Dividing these values by _**3**_ result in _**0.666**_ and _**4.644**_. This avoids the notes being perfectly aligned.

**Comment by AaronDavidNewman** [comment] 2021-02-28 01:34
I am just learning it, also.  But this my understanding so far:

`maxNegativeShiftPx` is only used to keep notes on the same staff from colliding if one is moved left.  The notes start out aligned to the left-most side of the bar, which is why it's too small to affect anything for the first tick (the 16th and 1/4 would collide).

`expectedDistance` is calculated only on the basis of previous note's duration in that staff, without regard to the widths.  It is 13px for the 1/4 on the top line, and 22px for the 1/4 on the bottom line.  But the width of the first tick context is 23.  This is why the 1/4 notes end up aligning - their starting X position are already to the right of where their `expectedDistance`, and they are already as far to the left as they can be without colliding with the previous note, so they are stuck.

Arbitrarily boosting `expectedDistance`   helps in this case, but in other cases it would push the notes too far to the right, since the ideal distances already consider the full width of the measure for all the note - you would be 'stealing' another note's width.  

The legacy logic placed the notes `expectedDistance` from the right edge of the previous note.  That was good for justification but it also had the issue of pushing notes too far to the right in some cases, since the computed distance is only based on duration of the notes and not their width. 

There is also this `evaluate()` piece, that kicks in if the notes exceed the width of the measure and reformats the notes.  I have not even started to understand this code yet.  It is not kicking in here, anyway, because the notes all fit in the measure so it doesn't  detect anything is wrong.  I think a solution will be to detect this condition and recalculate the distances.

**Comment by rvilarl** [comment] 2021-02-28 11:04
> ...
> I have a question about the formatter, the function `preFormat.shiftToIdealDistances:`
> 
> ```js
> errorPx = (ideal.fromTickable.getX() + ideal.expectedDistance) - (x + spaceAccum);
> ```
> 
> Shouldn't that include the `fromTickable.width`? ...
> 

@AaronDavidNewman would `calculateIdealDistances` the right place to consider the width issue? Changing:
```js
maxNegativeShiftPx = Math.min(maxNegativeShiftPx, context.getX() - prevContext.getX());
```
To:
 ```js
maxNegativeShiftPx = Math.min(maxNegativeShiftPx, context.getX() - prevContext.getX() - prevContext.width);
 ```
I get:
![image](https://user-images.githubusercontent.com/22865285/109416029-2d8d9c80-79bc-11eb-9fd3-6677b2ea9eb1.png)

**Comment by AaronDavidNewman** [comment] 2021-02-28 15:50
@rvilari I think I would need @0xfe to chime in here on what is 'right', or best.  But I have a couple of ideas and you are welcome to try them out.  I'm coming up with a more complete list of formatter tests for the unit test cases that includes some of these issues:

1.  The tick length that we use to calculate softmax could take the width into account.  We could multiply the tick length by the number of std deviations from the mean width, for instance.
2. We can detect this when the right edge of the previous tick overlaps the left edge of this tick.  We track this in `contextGaps` field.  We could then adjust the ticks heuristically and run softmax again, by increasing the tick length of the previous tick.

I don't think it will ever work consistently to change the offsets after softmax (the expected distance) has been calculated because of the nature of that function.  i.e. you can't consider the width _after_  you've calculated the distance, you need to wrap it into the distance calculation somehow (or use a different function than softmax altogether, but I don't know what that would be).

Here is another test case, a different manifestation of the same issue:

https://jsfiddle.net/AaronDavidNewman/8jL7b10v/

That seems a much more common problem because the beats are lined up very nicely, but the accidental gets mushed.

**Comment by AaronDavidNewman** [comment] 2021-02-28 21:21
OK, idea #1 is a big fail, because:

![image](https://user-images.githubusercontent.com/5438280/109433897-4f951800-79d8-11eb-98c2-c4e5559b2d63.png)

If a note fits in its proportional space, we want to leave it alone.  We only want to change the formatting if a note collides with its neighbor because it is too wide.  And we only know that after we've computed the expectedDistance.  So I will try the second approach.

**Comment by rvilarl** [comment] 2021-02-28 21:41
@AaronDavidNewman I was trying to figure out your idea 1. If there is anything you would like me to try just let me know. The accidentals' overlap was the first problem I saw and I got to issue #829 which is also open.

**Comment by AaronDavidNewman** [comment] 2021-02-28 21:55
@rvilarl if you look at my comment in that issue, you could try that.  Here is the change I have on my Smoosic fork in note.js:

![image](https://user-images.githubusercontent.com/5438280/109434847-c3d1ba80-79dc-11eb-82b1-39046177ad42.png)

This works great for this example, but I don't know that these are the right values (`Note.modifierPadding` ===10 is what I used), or if left and right padding should always be set together like I did, or if the mere presence of a modifier is the correct condition to check for.  I sort of just did what Mohit suggested.  It seems you have a lot of nice test cases, maybe you could try those.

**Comment by rvilarl** [comment] 2021-03-01 06:32
@AaronDavidNewman I tried this morning with several scores and the accidentals are shown correctly. However I get the same problems that I reported in #829 Clef Changes and Grace Notes that overlap with the notes. @0xfe stated _**"Ouch, that looks like a separate bug. It's possible ClefNote needs to be updated for the new formatter"**_. I use OpenSheetMusicDisplay to test and this is why I can check with a lot of MusicXML Scores.

**Comment by 0xfe** [comment] 2021-03-02 12:48
Good discussion folks -- sorry, I haven't had a moment to catch up on all this. @AaronDavidNewman or @rvilarl,  if you could send a PR with some broken formatter tests (in `tests/formatter_tests.js`), that would be great. (You can use the `tightNotes` as a reference.)

**Comment by AaronDavidNewman** [comment] 2021-03-02 22:09
>> if you could send a PR with some broken formatter tests (in tests/formatter_tests.js), that would be great

Done.  @rvilarl  I have not dug into the ClefNote issues, feel free :)   I needed the accidental padding to be correct to test my formatting changes.  I have got all of the problem cases working, _except_ the original one from this issue.  That is a tough one...you really need to track alignment cross-voices for that.  I don't know whether my changes will be keepers or not, but if we have all the cases working that will be a good start.

**Comment by rvilarl** [comment] 2021-03-03 12:59
The problem with the ClefNote appear only when modifying modLeftPx and / or modRightPx. Not with the unmodified code.

**Comment by AaronDavidNewman** [comment] 2021-03-03 18:12
That makes sense, because clefNote extends note.  Maybe we should open a separate issue for this.  We can either move the getMetrics padding to stemmableNote, or staveNote depending on what other note children this affects.

**Comment by rvilarl** [comment] 2021-03-04 19:52
@AaronDavidNewman Done see #845

**Comment by AaronDavidNewman** [comment] 2021-03-06 00:36
I (almost) did it!   Here are some examples (**was** refers to master branch, ** is now** to my changes).  Other tests are mostly the same - I think I am not always calculating the `lastContext` the same as before, because I sometimes come closer to the edge of the staff:

**was:**
![image](https://user-images.githubusercontent.com/5438280/110187852-73dd6400-7ddf-11eb-9af3-c52cb1b5b8e9.png)
**is now:**
![image](https://user-images.githubusercontent.com/5438280/110187835-632cee00-7ddf-11eb-8011-e3b3dda2c9e6.png)

**was:**
![image](https://user-images.githubusercontent.com/5438280/110187881-8bb4e800-7ddf-11eb-83f1-a6c03fd0f364.png)
**is now:**
![image](https://user-images.githubusercontent.com/5438280/110187897-966f7d00-7ddf-11eb-9318-360d6d8cc029.png)

**was:**
![image](https://user-images.githubusercontent.com/5438280/110187923-a7b88980-7ddf-11eb-8a99-a8dc0cc379ef.png)
**is now:**
![image](https://user-images.githubusercontent.com/5438280/110187952-b868ff80-7ddf-11eb-9412-53b049409309.png)

I'm still a ways from a pull request.  I'm afraid the `preFormat` code has changed quite a lot.  I'll try to tweak the code to fix these remaining issues (last example for instance could still be a little closer to the 16th note), then we can talk about how we pull it.

I introduced something called `widthTicks` which starts the same as tick value, used to calculate the softMax values.  If there are overlaps (collisions), I increase or decrease the `widthTicks` and recalculate softMax.  Once all the collisions are fixed, I look for collisions on different voices and do the same thing.  I don't set the context X until I have everything formatted correctly, or I run out of passes (currently set to 5).  So `shiftToIdealDistances` is pretty simple.

**Comment by 0xfe** [comment] 2021-03-06 12:57
Good job! I just started digging in this morning, and found a bug in how `negativeSpaceAccum` works (for which I haven't figured out a fix.

I also found that the original `preCalculateMinWidth` was correct, and the new one just adds duplicated spacing.

How does your fix affect the other tests?

**Comment by 0xfe** [comment] 2021-03-06 14:27
Digging in more:

1) the first two examples are corrected by simply adding pixels to the result of `preCalculateMinWidth` (below, I added 100px to it):

<img width="401" alt="Screen Shot 2021-03-06 at 9 19 29 AM" src="https://user-images.githubusercontent.com/241299/110210052-d5dcae80-7e5d-11eb-84e3-2b3b767f09ca.png">

This suggests to me that `preCalculateMinWidth` needs to be corrected to support softmax scaling, along with fixing how `negativeSpaceAccum` is used to render tighter scores.

2) I think your your last example is still wrong. The first notes after the rest should not be aligned. (That isn't fixed, AFAICT, by increasing the justification width.)

**Comment by rvilarl** [comment] 2021-03-06 14:55
@0xfe @AaronDavidNewman do you mean `preCalculateMinTotalWidht` in `formatter.js`?

**Comment by rvilarl** [comment] 2021-03-06 15:05
If this the case it makes obvious that the error is cumulative the second dot note in the lower staff in each staff is more disaligned to the left with this 100.
![image](https://user-images.githubusercontent.com/22865285/110211167-a9dd1f80-7e95-11eb-839c-8f2df7334ea1.png)

**Comment by rvilarl** [comment] 2021-03-06 15:12
The change in this function does not cause trouble with Clef Notes like #845:

![image](https://user-images.githubusercontent.com/22865285/110211349-7ea70000-7e96-11eb-837d-da4a9ed25a81.png)

 or Grace Notes:

![image](https://user-images.githubusercontent.com/22865285/110211392-b01fcb80-7e96-11eb-9fe4-49670c2c7596.png)

**Comment by 0xfe** [comment] 2021-03-06 15:15
I just pushed some changes to fix some bugs (and undo the recent preCalculateMinWidth PR.)

We still have two issues:

- preCalculateMinWidth should factor in softmax scaling
- the cross-voice formatting may end up aligning the wrong ticks if the softmax denominators across them happen to be the same.

**Comment by AaronDavidNewman** [comment] 2021-03-06 15:33
When I tried it, it seems like this one is not fixable just be changing the width to the measure.  But I haven't tried your latest change yet.

![image](https://user-images.githubusercontent.com/5438280/110211696-6bc40980-7e5d-11eb-8b56-329671558dbb.png)

>> I think your your last example is still wrong

Yes, the note after of the 16th note is now to the left of the note after the 8th note, but only by a few pixels.  Fixing `preCalculateMinWIdth' may fix this issue - I don't see it in Smoosic with this example and I do the width calculation differently.

There are some other test cases I added later where it seems like `preCalculateMinWidth` is really too low:

![image](https://user-images.githubusercontent.com/5438280/110211830-fdcc1200-7e5d-11eb-9922-c18e5584d7d8.png)

Trying your changes now, if it looks better I'll post the results here.

**Comment by rvilarl** [comment] 2021-03-06 15:50
If you want me later to try something, let me know. I wish you two lots of success!

**Comment by 0xfe** [comment] 2021-03-07 12:01
Thanks Aaron -- My last change seems to have fixed most of the issues with "overlapping" notes.

The `preCalculateMinWidth` fix was to remove a bandaid that made other scores a lot worse. The bandaid was double-counting the left modifier spacing (which just arbitrarily turned out to be correct in some cases.)

**Closed** 2021-03-07 12:40 UTC

**Comment by 0xfe** [comment] 2021-03-07 12:47
Okay, the alignment issue is fixed:

<img width="516" alt="Screen Shot 2021-03-07 at 7 44 18 AM" src="https://user-images.githubusercontent.com/241299/110240261-19e0b980-7f19-11eb-86ec-6a0990db93a0.png">

It had to do with the shift limit for negative shifts. The softmax calculations turned out to be correct, it's just the left-shifting of the notes went too far, sometimes aligning notes with different tick contexts across voices.

**Comment by 0xfe** [comment] 2021-03-07 12:59
Also added a `globalSoftmax` option that sets the proportions based on all notes across all formatted voices.

<img width="538" alt="Screen Shot 2021-03-07 at 7 58 24 AM" src="https://user-images.githubusercontent.com/241299/110240671-13534180-7f1b-11eb-8fe4-d2078f437c86.png">

**Comment by AaronDavidNewman** [comment] 2021-03-07 20:27
This looks really nice, Mohit, thanks!  It seems to address all the points we mentioned in this thread.

What is the rule of thumb for when to use globalSoftmax?  All of my test cases seem fine without it.

I still think `preCalculateMinTotalWidth` is returning a value that is too low in some cases. 

![image](https://user-images.githubusercontent.com/5438280/110253644-02bdbe00-7f51-11eb-9881-ded0cb026157.png)

**Comment by rvilarl** [comment] 2021-03-07 20:40
> I still think `preCalculateMinTotalWidth` is returning a value that is too low in some cases.

I also do, have a look at #845

**Comment by 0xfe** [comment] 2021-03-07 20:46
Yes, `preCalculateMinTotalWidth` is still wrong, that should be separate issue. This specific issue is fixed (I hope.)
