### ISSUE TITLE
Vexflow Typescript File by File Migration

### ISSUE THREAD

**Issue by wassertim** [0xfe/vexflow#850] opened 2021-03-13 20:14 UTC
After @wassertim and @rvilarl had a discussion we propose to migrate to typescript file by file, providing support for js and ts simultaneously.

First PR will contain infrastructure for ts and eslint.

And then we will create many PRs with ts files substituting js files.

@0xfe

**Comment by 0xfe** [comment] 2021-03-13 20:40
Good plan. Much easier to review -- we can start with small chunks, and as we gain confidence, start adding bigger chunks to the PRs.

As part of the build infrastructure (first commit): add `src/dummy.ts` and confirm that it lints, and builds.

After the build infrastructure, lets do the test infrastructure. And add a `tests/dummy_tests.ts` that just does `ok(true)`.

Once that's good, we can try some independent source files (music.js, tuning.js, or fraction.js), one by one and use those as strawmen to decide on style, etc. To start, I suggest `src/music.js` and `tests/music_tests.js`. 

Please also tag @mscuthbert in the reviews.

**Comment by rvilarl** [comment] 2021-03-13 21:53
@0xfe the plan is to add the infractstructure to the current project, see that all the tests pass. And then on a second to change one file form js to ts.

**Comment by 0xfe** [comment] 2021-03-13 22:34
Thanks @rvilarl -- that sounds good, just also requesting that the first PR includes a `dummy.ts` file or something (which we can remove later) so we know that the build/lint infrastructure does what it's supposed to do. Otherwise, the only signal we get is that tests pass, not that the build infrastructure works.

**Comment by rvilarl** [comment] 2021-03-13 22:37
@0xfe where do you want us to make the PR, on master? If you want to check that the infracstructure is running ok, I suggest to change element.js to element.ts in order to make it participant on the complete set of tests.

**Comment by 0xfe** [comment] 2021-03-13 22:51
Yes, `master` is good, then we won't have to worry about keeping branches in sync. I don't think `element.js` is a good first class because it has a huge downstream effect. If you don't want to create a `dummy.ts`, then try migrating `music.js` or `tuning.js` which are less invasive?

**Comment by rvilarl** [comment] 2021-03-13 22:56
You are right. It is very invasive but proving that element with minor changes pass all the tests provides a lot of confidence. And being an abstract class we can be almost sure that we do not affect the client applications. Wouldn't you agree?

**Comment by rvilarl** [comment] 2021-03-15 21:32
@0xfe I am enjoying the experience a lot and I have two questions:
- does the package @types/vexflow belong to this repo? I would like to open issues for the topics above.
- once the first commit is ready I would proposed a second one with three files, I am preparing it. This one would include tuning.js, elements.js and tickable.js. Is that ok?

**Comment by sschmidTU** [comment] 2021-03-16 14:37
@types/vexflow belongs to DefinitelyTyped, an external project where people share/build typescript definitions for javascript projects that don't have typescript definitions yet.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/vexflow

**Comment by 0xfe** [comment] 2021-03-16 14:55
@rvilarl glad you're enjoying it. I agree with @sschmidTU about `types/vexflow`.

The second PR should be `tests/music_tests.js`.

The next one `tuning.js` and `fraction.js` (along with tests please.)

**Comment by 0xfe** [comment] 2021-03-17 11:14
I just merged #851. Really glad to see this make progress! Great job driving this @wassertim and @rvilarl!

**Comment by rvilarl** [comment] 2021-03-19 14:12
@0xfe today @wassertim and I will make a PR with the test infrastructure and the migration of the music_test. There we have separated the js testing and the ts testing on two different files leaving the js infrastructure as it is to keep the changes as low as possible. That is:
- concatted files and flow.html
for the ts files we have to compile. Here we use in Gruntfile:
- a new webpack target buildTest
- a new qunit target flow_ts.html

**Comment by rvilarl** [comment] 2021-03-20 09:45
@0xfe we are making a final review before we make the PR. In this review I have realised that **eslint-config-airbnb-base** is included in package.json. If there is the wish to fullfil a eslint standard, I believe the right time to consider that is now that we have started a complete migration. I refer to **airbnb**, **google** or **standard**.

**Comment by mscuthbert** [comment] 2021-03-20 10:50
This is so exciting -- already the first commit has revealed some things that I have been doing incorrectly in my own code that references VexFlow, and will hopefully help me find more errors.

One other thing that I've found helpful in doing a gradual js to ts migration on a released/frequently-used code base is to not do conversions to typing methods and variables `private` unless you are sure that there is an exact public interface to get the same information/functionality.  And even then, `protected` (which allows access in subclasses) is probably better for most variables for some time.  (In one project, I specifically have one file remaining as .js in order to access some private functions in `lit-element` that are very important and have no public interface, in order to bypass typescript's hiding of private variables).  

The exception would be for cases where we know (i.e. @0xfe knows) that there's a plan to refactor the private interface in the near future and that forbidding people from accessing the internals would save them grief when they next update Vexflow.

Right now, there are aspects of staff-line configuration that have no perfect public interface so I go into the private interface in music21.

**Comment by 0xfe** [comment] 2021-03-20 11:43
@rvilarl new `buildTest` target is good, but why two html files? You can include both targets in `flow.html` no?

@rvilarl for lint, let's go with `airbnb`

@mscuthbert thanks for the input. Re: private vs public -- I've tried hard to create getters/setters for variables that should be public, and, except for `tables.js`, users should not be reaching in. If you could create an issue listing any internals that you use, I can think about how to expose them properly.

**Comment by rvilarl** [comment] 2021-03-20 11:55
@0xfe, @wassertim is giving it a try at a single flow.html. I did not manage it. The problem is that the test js files are thought to be concatted and then downloaded together with vexflow-debug.js. However the ts test files are compiled with the required sources and do not need vexflow-debug.js. We will see how this ends.
I will setup airbnb.

**Comment by rvilarl** [comment] 2021-03-20 22:24
@0xfe @mscuthbert @wassertim I believe it really makes sense to keep **typescript strict** and to use **airbnb**. Today with airbnb Ihave realised that all the methods in Music are static, there is no need to make instances of Music using new. I have also found a bug in the test infrastructure and that eslint was not configured. The files in test were not being checked. I believe this has a very good potential to find bugs. However there are changes to do! The changes do impact on other classes, although, so far I would say in a minor way.

**Comment by rvilarl** [comment] 2021-03-22 07:11
@0xfe @mscuthbert: @wassertim is working in a single test qunit, it is looking very promising! In the meanwhile I will send a push request fixing the elements in the comment above to start with **airbnb** on TS files:
- **eslintrc**:  now configured in a single file with airbnb support for TS files
-  **Gruntfile Package**: bug disabling lint in tests folder fixed. Babel removed (vexflow_min is reduced 80K :) )
- **Music**: Methods are now static and some other minor changes. 
- **Vex**: RuntimeError now extends Error.
- **Accidental KeyManager and music_test**: adapted to use static methods of Music.

**Comment by 0xfe** [comment] 2021-03-22 14:24
Thanks @rivlarl -- can you separate the eslintrc changes please?

Great to hear about removing Babel!

Re: `Music` please don't change the interface. It'll break external users. :-)

**Comment by rvilarl** [comment] 2021-03-22 16:18
@0xfe the number of files in front of us is huge and now I know how to proceed, without airbnb. This will require less changes :). I suggest to make an additional PR with sources ony while @wassertim finalizes the single qunit solution. If you agree I will PR `tuning.ts` and `fraction.ts` once we finish with the removal from babel.

**Comment by sschmidTU** [comment] 2021-03-23 17:58
@mscuthbert 
> (In one project, I specifically have one file remaining as .js in order to access some private functions in `lit-element` that are very important and have no public interface, in order to bypass typescript's hiding of private variables).
You probably know this, though i think it should be mentioned in the context you're refering: you can access any private member in typescript just like in javascript, by casting it to any. e.g. `(stavenote as any).privateVariable`
Of course it's not pretty and you don't want to cast to any all the time, but it's a similar level of "bypassing".

**Comment by mscuthbert** [comment] 2021-03-24 18:45
> You probably know this, though i think it should be mentioned in the context you're refering: you can access any private member in typescript just like in javascript, by casting it to any. e.g. `(stavenote as any).privateVariable`
> Of course it's not pretty, it removes type checks, and you don't want to cast to any all the time, but it's a similar level of "bypassing".

I didn't know that.  THANK YOU!

**Comment by rvilarl** [comment] 2021-03-28 13:31
@0xfe the test infrastructure requires some more time. Would it be fine to go on with a PR with `Tuning` and `Fraction` without TS tests, to keep on making progress?

@wassertim FYI

**Comment by 0xfe** [comment] 2021-03-28 13:35
Okay, let's do `Fraction` then `Tuning`. I'm hesitant to diverge too far without TS tests. Thanks!

**Comment by rvilarl** [comment] 2021-03-28 20:06
@0xfe I just realised that you say 'then' and not 'and'. If you want me to take one class out of the PR, just let me know. Please note that the classes are being tested with the js test files, they are not disabled.

**Comment by mscuthbert** [comment] 2021-03-30 00:48
Yes, we can convert tests to typescript on a file-by-file basis but they should still run even before they are converted.

It's often the case with JS to TS conversion that the tests are designed to load the entire system and so if there are parameter problems (like the formatter one just noticed) that they won't work if they're converted too early.  In music21j I had to convert the whole system to TS before starting the test conversion also.

**Comment by rvilarl** [comment] 2021-03-30 11:11
@mscuthbert @0xfe: in regards to testing I suggested to have two separated test files one `flow.html` and one `flow_ts.html` one for js and one for ts due to the fact that you describe above: the different approach in testing (TS test contain the code and do not test against a external library)

@wassertim is putting a lot of effort to get a single test (see #858) and he is almost there, but I think that the number of changes will be more than the one required with two tests.

I also like the two tests approach because it gives a visual feedback on the progress (lenght of the dotted lines) and in any case the two tests is an intermediate state, the js test will disappear at the end of the migration.

![image](https://user-images.githubusercontent.com/22865285/112969101-3b664700-914d-11eb-821a-9d58796b94a5.png)

**Comment by rvilarl** [comment] 2021-04-01 12:43
@0xfe @mscuthbert I would suggest to go for element and tickable, once we finish with fraction and tuning. I have them ready to go! And this are key steps that will allow us to get formatter. :)

**Comment by 0xfe** [comment] 2021-04-01 13:02
@rvilarl Let's target a single test please. I understand it's a heavier lift, but once the infrastructure is ready things will be simpler. (And the process of getting it all working will be a big milestone.)

Re: element and tickable, that sounds fine, and okay to start on it too, however I'd like to merge the tests before any more src/ files.

**Comment by rvilarl** [comment] 2021-04-01 14:00
@0xfe what about starting with two qunit tests (flow.html & flow_ts.html for typescript) and then once @wassertim is ready we merge them in one qunit test. Please see the comment above with the screen capture with two tests.

**Comment by 0xfe** [comment] 2021-04-01 14:44
That sounds good to me.

**Comment by rvilarl** [comment] 2021-04-02 13:03
@0xfe @mscuthbert @wassertim I will make a PR with the two tests discuss above. It is also not to be merged in a first instance it is to discuss on the tests modifications.

**Comment by rvilarl** [comment] 2021-04-03 05:26
#873 is almost ready! @wassertim good job! I agree with you once it is merged the migration speed will be much higher.

@0xfe @mscuthbert @wassertim I suggest the following two PRs:
1) migrate tests for Tuning and Fraction
2) go for Element and Tickable including tests

**Comment by 0xfe** [comment] 2021-04-03 12:02
Sounds good.

**Comment by rvilarl** [comment] 2021-04-10 22:10
@0xfe @wassertim  the migration of the tests is getting too complex without having all the sources migrated. I would suggest to focus on the src and once this is finish migrating the test.

**Comment by rvilarl** [comment] 2021-04-10 22:12
@0xfe @wassertim we do not have to forget that the tests in js are running testing the migration anyway

**Comment by 0xfe** [comment] 2021-04-10 22:15
It's fine with me. At least we have the TS tests working, so that's good.

**Comment by rvilarl** [comment] 2021-04-10 23:28
@0xfe I have done 3 quick wins PRs with small files migrated, I am wishing to celebrate the >2% TS :)

**Comment by rvilarl** [comment] 2021-04-11 20:13
@wassertim we control progress now with #884 I think this one can be closed.

We have reached > 2% TS in project! :+1:

**Comment by 0xfe** [comment] 2021-04-12 00:04
Yay for 2%! 🎉

**Comment by rvilarl** [comment] 2021-07-04 14:06
@0xfe you can close this

**Closed** 2021-07-04 14:20 UTC
Labels: typescript
