### ISSUE TITLE
4.0.1

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1281] opened 2022-01-01 19:02 UTC
@0xfe @ronyeh @AaronDavidNewman @mscuthbert @sschmidTU @h-sug1no HappyNew Year! :)

I would like to start a discussion on when to release a 4.0.1. I would suggest to close #1155 this issue is already quite long. There are mainly two topics that I can think of:
- beta or release
- content

**Comment by rvilarl** [comment] 2022-01-01 19:03
Let us make 4.0.1 a release, we will get more feedback from users and they can always decide to stay in 3.0.9 or 1.2.93

Thumbs up release
Thumbs down beta

**Comment by rvilarl** [comment] 2022-01-01 19:08
Content:
- Vexflow Patch topics because I am aiming to get an OSMD release with Vexflow 4.x and use this one in PianoPlay.
- Vertical collisions #411 @AaronDavidNewman is working on.

**Comment by ronyeh** [comment] 2022-01-01 20:10
Happy New Year!

Sure, I'll close the old 4.0.0 issue to move the discussion here. 

Here are several small things I'd like to get into 4.0.1:
- documentation for build and release 
- documentation for adding fonts
- tweak the files included in package.json so that flow.html can run directly from unpkg.com. I think this will enhance our ability to do quick manual visual regression checks.
- fix some of our imports throughout the code base so that  ESM tests work. 

There are no major things I want to get merged into 4.0.1. 

However, I'd still call it a beta until we slow down a bit on the PRs and have a chance to test a single build for a few days without a recent merge possibly introducing unknown issues or circular dependencies. 😂

I assume npm requires us to increment the version number even if it's behind the beta dist tag. So I'd be happy with a succession of quick beta releases: 4.0.1, 4.0.2, just to test out the release script and do sanity checks. If we either merge or set all our PRs to draft, we can all inspect and bless the current build and make a official release 4.0.3 or something. If we discover issues, we can fix and keep incrementing the patch number but without the beta tag. 

I'd be happy to manage the release to npm and GitHub if Mohit grants me the npm publish right. (Or Mohit can do it himself if we all declare the official release is ready and we have no PRs we want to merge.) Worst case if we mess something up on an official release, I can bump the patch version number. 😑 I am planning to use the release-it package to help automate some steps for releasing to both npm and GitHub.

https://www.npmjs.com/package/release-it

I've tested release-it on my own npm package and it works great. Let me know if there is an alternative package that you think is better / more popular with the cool kids.

**Comment by ronyeh** [comment] 2022-01-01 20:15
Previous discussion at https://github.com/0xfe/vexflow/issues/1155

**Comment by 0xfe** [comment] 2022-01-08 12:09
There's going to be at least one major API change that we should document. @ronyeh where do you track the changelog for release?

@rvilarl we should be super clear about the API changes around `addDot`, `addDotToAll`, `addAnnotation`, etc. and have instructions with some before/after examples. This one is mildly disruptive to users, but vastly improves Vexflow's dependency problem.

**Comment by 0xfe** [comment] 2022-01-08 12:11
Ron, it's cool to bump the patch levels and mark the package as beta.

**Comment by ronyeh** [comment] 2022-01-09 03:10
Hi all,

Detailed changelog is on the wiki: 
- https://github.com/0xfe/vexflow/wiki/Changelog-ver-4.0
- https://github.com/0xfe/vexflow/wiki/Changelog

Each notable version will have its own page with a detailed discussion of changes. Smaller version bumps can have their changes added at the top of the page.

Rodrigo, feel free to edit the 4.0 page with the things you recently changed that are not backwards compatible with 3.0.9. You can list them in the [Breaking Changes section](https://github.com/0xfe/vexflow/wiki/Changelog-ver-4.0#breaking-changes). You can replace the **More / Add Detail Here** sections. Don't worry about formatting. Once you're done, let me know and I can rearrange if necessary as this document grows.

We will keep a bullet point summary of changes in the repository, at: https://github.com/0xfe/vexflow/blob/master/CHANGELOG.md

The repo CHANGELOG.md has too much detail at the moment. The extra detail will be moved over into the wiki. The repo doc will always point to the wiki changelog.

**Comment by ronyeh** [comment] 2022-01-24 04:42
Hello all,

To test the release script, I just published `4.0.1-alpha.0` to npm and github.

https://github.com/0xfe/vexflow/releases/tag/4.0.1-alpha.0

https://www.npmjs.com/package/vexflow?activeTab=versions

To install in your project, type:
```
npm install vexflow@alpha
```

Please let us know if there are any issues! I think we are getting close to a full release. There are currently 5 open PRs. Once those are resolved, I think @0xfe can push the launch button, haha.

**Comment by rvilarl** [comment] 2022-01-24 22:31
It is 6 PRs I have one in draft because it builds on the one with the `dots` discussions.

**Comment by ronyeh** [comment] 2022-01-30 21:34
I just published https://github.com/0xfe/vexflow/releases/tag/4.0.1-alpha.1

I checked that it builds correctly and flow.html tests "pass" (i.e., no runtime errors).

I see in the GitHub issues that there may be some visual regressions. Let's diagnose & fix so we can move up to beta and then to full release.

**Comment by ronyeh** [comment] 2022-02-17 01:14
Looks like there are no outstanding visual regressions from 3.0.9.

I just published a beta. Install with:

```
npm install vexflow@beta
```

I ran all the tests successfully, and flow.html tests look good.

I think we're close to a full release. Please try out this new beta and let us know if there are any issues!

**Comment by rvilarl** [comment] 2022-02-27 06:00
@ronyeh this one does work with OSMD Thank you!
I updated https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1148 and all tests passed.
@sschmidTU FYI

**Comment by ronyeh** [comment] 2022-03-01 09:52
We're getting close! I think we will publish a release candidate soon and then if no complaints come in, we can promote it to a full 4.0.1 release.

I started working on a overview document for VexFlow 4: https://github.com/0xfe/vexflow/wiki/VexFlow-4

At the bottom is a complete list of all commits between 3.0.9 and 4.0.1! (Spoiler: it's over 1600 commits).

**Comment by ronyeh** [comment] 2022-03-21 22:47
Hello everyone!

I just pushed a release candidate to NPM:

```
npm install vexflow@rc
```

Please give it a try on your projects. If there are no critical issues, we plan to ship this version as **VexFlow 4**. Other PRs will go into the next patch or minor release.


Tagging some other folks so you can give this version a try before the VexFlow 4 release:
@mscuthbert @gristow @AaronDavidNewman

**Comment by rvilarl** [comment] 2022-03-21 23:06
@ronyeh OSMD runs fine with vexflow@rc. Let us release as soon as possible!

**Comment by gristow** [comment] 2022-03-24 15:54
Looks good to me -- thanks for the amazing work on this @ronyeh!

**Closed** 2022-03-24 20:51 UTC
Labels: release

**Comment by ronyeh** [comment] 2022-03-24 21:52
VexFlow 4 has been released!

```
npm install vexflow
```

https://github.com/0xfe/vexflow/releases/tag/4.0.1

https://www.npmjs.com/package/vexflow

**Comment by mscuthbert** [comment] 2022-03-25 00:44
This is incredible amazing news.  Congrats to everyone who worked so hard on this!
