### ISSUE TITLE
Stem extensions reaching to middle line

### ISSUE THREAD

**Issue by mscuthbert** [0xfe/vexflow#637] opened 2018-07-31 19:55 UTC
One of the most common music engraving rules that Vexflow does not respect is the notion that by default a stem going the normal direction should reach at least to the middle line.  That is, a note above B-above-treble clef, or below B-below-treble-clef needs its stem extended.

This code seems to work and does not interfere with additional stem length based on flags, and is overridden by beams w/o regression of current behavior.

(adapted slightly, because I was working in the sandbox, so there may be typos).

I just want to be sure that putting this in the constructor of StaveNote is the correct thing to do.

```
const st = this.getStem();
if (!st) return;
const currentExtension = st.getExtension();
if (this.stem_direction === Stem.UP) {
  const noteheadIndex = this.note_heads.length - 1;
    if (this.note_heads[noteheadIndex].line < -1.5) {
       st.setExtension(currentExtension + (this.note_heads[noteheadIndex].line + 1.5) * -5);
    }
} else {
    if (this.note_heads[0].line > 6.5) {
         st.setExtension(currentExtension + (this.note_heads[0].line - 6.5) * 5);
    }
}
```

**Comment by 0xfe** [comment] 2020-04-02 19:54
Not sure where we landed here -- if you can produce some screenshots of current and expected behavior, I can take a look. Closing for now due to age.

**Closed by 0xfe** 2020-04-02 19:54 UTC

**Comment by mscuthbert** [comment] 2020-04-02 20:05
Sure, thing, will do!
