### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by lilybucher** [0xfe/vexflow#530] opened 2017-01-25 10:48 UTC
I am having a very difficult time using vexflow due to either me not finding the proper location for the API documentation or maybe these docs are missing.

Just having an API wiki specifying function arguments would be a huge help...

For example, I cannot find documentation on

1. note durations (from a number representing a fraction of a whole note)
2. creating rests

**Comment by lpeppe** [comment] 2017-01-25 10:58
I had your same problem when I started using vexflow. The way I solved it was to use PHPStorm and open the vexflow-debug.js in the structure view. In this way you can see all the VexFlow classes and methods.
 As for your 2 problems:
1. the note durations are (in order) w, h, q, 8, 16
2. to create a rest you just need to add a "r" at the end of the duration. For example wr is a whole rest, hr is a half rest and so on

**Comment by gaspard** [comment] 2017-01-25 12:03
Thanks for your help :-) I finally found out about the durations but am now stuck with adding lyrics. If my voice has StaveNotes, it works but when I use TextNote, I get "NoContext"... Any clue ?

```js
// StaveNote works here but not TextNote ??
// new VF.StaveNote
// ( { keys: [ 'a/3' ]
new VF.TextNote
( { text: takadimi ( position )
  , duration: duration.toString ()
  // , duration_override: { numerator: duration, denominator: 1 }
  }
)
```

**Comment by SalahAdDin** [comment] 2017-02-27 13:43
Yes, @gaspard i'm agreed with you.

**Comment by gristow** [comment] 2017-06-19 15:38
Duplicate of #513 -- and you're absolutely right. We could definitely use help in providing clearer documentation for VexFlow's API. As you come gotchas like you did in #531, if you think to document them in the wiki it'll forever help future VexFlow users!

**Comment by tmcw** [comment] 2017-10-03 22:17
I'd be happy to adopt this task, if there's interest on the developers part, and implement automated API documentation.

**Comment by SalahAdDin** [comment] 2017-10-04 13:05
@tmcw Please!

**Comment by gristow** [comment] 2017-10-04 17:08
Yes, @tmcw, that would be wonderful. A great place to start might be creating documentation for the major classes, documenting especially the properties available on the various `options` objects.

Given the wide support that JSDoc now has (in particular, WebStorm & VSCode do a great job of tracking types & properties from JSDoc), I wonder if it's time we move in that direction instead of Docco. @0xfe do you have any objection to moving towards JSDoc?

Some code commenting is already close to correct JSDoc -- tuplet.js for instance just needs to have the parameters of the `options` object reformatted to something like this:

``` javascript
/**
 * @param {object} options
 * @param {number} options.num_notes fit this many notes into...
 * @param {number} options.notes_occupied ...the space of this many notes
 */
```
Other classes will need much more attention to document all of their properties.

**Comment by loganknecht** [comment] 2018-05-21 18:02
Bumping this because I have spent some time looking for API documentation and have not had success. The [API link](http://public.vexflow.com/docs/) in the wiki directs me to a page that is not super helpful.

Please keep up the great work though! This is an incredibly impressive library and I love how much the community is working together to advance and maintain this!

**Comment by SalahAdDin** [comment] 2018-05-21 23:09
@tmcw please man.

**Comment by rvilarl** [comment] 2021-07-16 05:02
Hi all, I am updating / doing documentation using typedoc, help would be appreciated.

@0xfe As I said somewhere else, it would make sense to release a version 4.0.0a to provide visibility on the documentation and the typescript approach.

**Comment by ronyeh** [comment] 2021-10-05 21:12
I agree that API docs and general "how to use" docs are super important for increasing adoption of VexFlow.

As we get the 4.0 release ready, we need to prioritize this.

**Closed** 2021-11-20 11:58 UTC
Labels: 4.0
